### ISSUE TITLE
Remember me 機能の実装

### ISSUE THREAD

**Issue by ywenli** [ywenli/health_app#26]
# What is this?
任意でユーザーのログイン状態をブラウザを閉じた後でも有効にするRemember me機能を実装します

# TODO
- [x] remember_digestをUserモデルに追加
- [x] メソッドを作る
	- [x] Use.new_token ランダムなトークンを返す 
	- [x] User.digest トークンを暗号化する
	- [x] cookies.signed IDを暗号化する
	- [x] remember ユーザーをDBに記憶する
	- [x] cookies.signed 暗号化したIDからユーザーを探しだす
	- [x] authenticated? トークンを照合
	- [x] forget 永続化を破棄
- [x] Sesstion コントローラーを修正
- [x] Userモデルのテストを作る
- [x] Remember me の view を作る
- [x] Remember me に scss を追加
- [x] Remember me の controller を作る
- [x] テストを作る

# NOTE
なし
