### ISSUE TITLE
プロフィール編集機能の実装

### ISSUE THREAD

**Issue by ywenli** [ywenli/health_app#28]
# What is this?
ユーザーのプロフィール情報を編集できるようにします

# TODO
- [x] editアクションの追加
- [x] テストを追加
- [x] プロフィール編集フォームを作る
	- [x] フォームをパーシャルにする
	- [x] signupとeditにrender 'form' を追加
- [x] ユーザーだけが自分のプロフィール編集できるようにする
	- [x] logged_in_userを作る（非ログイン時にログインを求める）
	- [x] 他のユーザーは編集を許さず、ホーム画面にリダイレクトさせる
- [x] ログイン後は編集ページにリダイレクトさせる（firiendly forwarding）
- [x] loginとlogoutページへのroutingを追加（追加し忘れていました）

# NOTE
なし
